---
 - hosts: db
   become: true
   tasks:
     - name: Installing mysql-server on target hosts
       apt:
        name: mysql-server
        state: present
        update_cache: yes
     - name: enable and start mysql service
       command: service mysql start && service mysql enable

