---
 - hosts: db
   become: true
   tasks:
     - name: Installing mysql-server on target hosts
       apt:
        name: mysql-server
        state: present
        update_cache: yes
     - name: start mysql service
       service:
         name: mysql
         state: started
         enabled: yes
