---
 - hosts: controlhost
   become: true
   tasks:
     - name: Install list of utilities/tools on local machine
       apt: name={{item}} update_cache=yes state=present
       with_items:
         - curl
         - wget
