--- 
- 
  become: true
  hosts: web
  tasks: 
    - name: Install packages 
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - nginx
        - python-pip
        - python-virtualenv
      notify: nginx-restart

  handlers:
    - name: nginx-restart
      service: name=nginx state=restarted
