---
 - hosts: web
   become: true
   tasks:
     - name: Update the repository cache and update package "nginx" to latest version using default release squeeze-backport
       apt: 
        name: nginx 
        state: present
        update_cache: yes
